### ISSUE TITLE
shape issue

### ISSUE THREAD

**Issue by ys7yoo** [ys7yoo/face-detection-cascade-cnn#2]
```
>>> net_12 = model.detect_12Net(input_12_node,target_12_node)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yyoo/src/face-detection-cascade-cnn/model.py", line 44, in __init__
    self.conv2_shape = tf.concat(0,[[-1],[tf.reduce_prod(tf.slice(tf.shape(self.h_conv2),[1],[3]),0)]])
  File "/home/yyoo/tf10/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1112, in concat
    tensor_shape.scalar())
  File "/home/yyoo/tf10/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py", line 847, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (2, 1) and () are incompatible
```

**Comment by ys7yoo** [comment]
tf.concat AP has changed

https://www.tensorflow.org/api_docs/python/tf/concat
https://github.com/tensorflow/tensorflow/issues/7031
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/udacity/6_lstm.ipynb
